version: '3.7'
services:
  angular:
    build: ./laser-chess-frontend
    image: tojatos/laser-tactics-frontend-dev
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - fastapi

  fastapi:
    build: ./laser-chess-backend
    image: tojatos/laser-tactics-backend-dev
    restart: always
    command: python -m app.main
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:admin@db:5432/laserchess
      - HOST=0.0.0.0
      - PORT=80
      - ROOT_PATH=

  db:
    restart: always
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=laserchess
    expose:
      - 5432

volumes:
  postgres_data:
