services:
  angular:
    build: ./laser-chess-frontend
    image: tojatos/laser-tactics-frontend-dev
    restart: unless-stopped
    ports:
      - '8080:8080'  # ng serve
      - '49153:49153' # Webpack live reload
    depends_on:
      - fastapi
    volumes:
      - ./laser-chess-frontend:/app  # Mount source code
      - /app/node_modules  # Prevent overwriting node_modules

  fastapi:
    build: ./laser-chess-backend
    image: tojatos/laser-tactics-backend-dev
    restart:  unless-stopped
    command: python -m app.main
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:admin@db:5432/laserchess
      - HOST=0.0.0.0
      - PORT=80
      - ROOT_PATH=
      - FE_HOST=localhost::8080

  db:
    restart: unless-stopped
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=laserchess
    expose:
      - 5432

volumes:
  postgres_data:
