version: '3.7'
services:
  angular:
    build:
      context: ./laser-chess-frontend
      args:
        BASE_HREF: "/laser-tactics/"
    ports:
      - 2346:80
    depends_on:
      - fastapi
    #command: >
      #ng serve --host 0.0.0.0 --port 8080 --proxy-config ./src/proxy.conf.docker.json --base-href="/laser-tactics/" --disable-host-check


  fastapi:
    build: ./laser-chess-backend
    restart: always
    command: python -m app.main
    ports:
      - 2345:80
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:admin@db:5432/laserchess
      - HOST=0.0.0.0
      - PORT=80

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=laserchess
    expose:
      - 5432

volumes:
  postgres_data:
