export enum PieceType {
  BEAM_SPLITTER = "BEAM_SPLITTER",
  BLOCK = "BLOCK",
  DIAGONAL_MIRROR = "DIAGONAL_MIRROR",
  HYPER_CUBE = "HYPER_CUBE",
  HYPER_SQUARE = "HYPER_SQUARE",
  KING = "KING",
  LASER = "LASER",
  MIRROR = "MIRROR",
  TRIANGULAR_MIRROR = "TRIANGULAR_MIRROR",
  UNKNOWN = "UNKNOWN"
}

export enum PlayerType {
  PLAYER_ONE = "PLAYER_ONE",
  PLAYER_TWO = "PLAYER_TWO",
  NONE = "NONE"
}

export enum PieceColors {
  BLUE = "_BLUE",
  RED = "_RED"
}

export enum GameEvents {
  PIECE_ROTATED_EVENT = "PIECE_ROTATED_EVENT",
  PIECE_MOVED_EVENT = "PIECE_MOVED_EVENT",
  TELEPORT_EVENT = "TELEPORT_EVENT",
  LASER_SHOT_EVENT = "LASER_SHOT_EVENT",
  PIECE_TAKEN_EVENT = "PIECE_TAKEN_EVENT",
  PIECE_DESTROYED_EVENT = "PIECE_DESTROYED_EVENT",
  GIVE_UP_EVENT = "GIVE_UP_EVENT",
  OFFER_DRAW_EVENT = "OFFER_DRAW_EVENT",
  TIMEOUT_EVENT = "TIMEOUT_EVENT"
}

export enum GamePhase {
  NOT_STARTED = "NOT_STARTED",
  STARTED = "STARTED",
  PLAYER_ONE_VICTORY = "PLAYER_ONE_VICTORY",
  PLAYER_TWO_VICTORY = "PLAYER_TWO_VICTORY",
  DRAW = "DRAW"
}

export enum ButtonTypes {
  LASER_BUTTON = "LASER_BUTTON",
  RIGHT_ARROW_BUTTON = "RIGHT_ARROW_BUTTON",
  LEFT_ARROW_BUTTON = "LEFT_ARROW_BUTTON",
  ACCEPT_BUTTON = "ACCEPT_BUTTON"
}

export enum EventsColors {
  MOVE_EVENT = "yellow",
  ROTATE_EVENT = "green",
  PIECE_TAKEN = "orange",
  PIECE_DESTROYED = "red",
  TELEPORT_EVENT = "blue"
}

export enum Theme {
  CLASSIC = "CLASSIC",
  WOOD = "WOOD",
  WOOD2 = "WOOD2",
  BLACK_AND_WHITE = "BLACK_AND_WHITE",
  CRYSTAL = "CRYSTAL"
}
