export enum PieceType {
  BEAM_SPLITTER = "BEAM_SPLITTER",
  BLOCK = "BLOCK",
  DIAGONAL_MIRROR = "DIAGONAL_MIRROR",
  HYPER_CUBE = "HYPER_CUBE",
  HYPER_SQUARE = "HYPER_SQUARE",
  KING = "KING",
  LASER = "LASER",
  MIRROR = "MIRROR",
  TRIANGULAR_MIRROR = "TRIANGULAR_MIRROR",
  UNKNOWN = "UNKNOWN"
}

export enum PlayerType {
  PLAYER_ONE = "PLAYER_ONE",
  PLAYER_TWO = "PLAYER_TWO",
  NONE = "NONE"
}

export enum PieceColors {
  BLUE = "_BLUE",
  RED = "_RED"
}

export enum GameEvents {
  PIECE_ROTATED_EVENT = "PIECE_ROTATED_EVENT",
  PIECE_MOVED_EVENT = "PIECE_MOVED_EVENT",
  TELEPORT_EVENT = "TELEPORT_EVENT",
  LASER_SHOT_EVENT = "LASER_SHOT_EVENT",
  PIECE_TAKEN_EVENT = "PIECE_TAKEN_EVENT"
}

export enum GamePhase {
  NOT_STARTED = "NOT_STARTED",
  STARTED = "STARTED",
  PLAYER_ONE_VICTORY = "PLAYER_ONE_VICTORY",
  PLAYER_TWO_VICTORY = "PLAYER_TWO_VICTORY",
  DRAW = "DRAW"
}

export enum ButtonTypes {
  LASER_BUTTON = "LASER_BUTTON",
  RIGHT_ARROW_BUTTON = "RIGHT_ARROW_BUTTON",
  LEFT_ARROW_BUTTON = "LEFT_ARROW_BUTTON"
}
