apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: E:\bin\kompose.exe convert -f .\docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: angular
  name: angular
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: angular
status:
  loadBalancer: {}
