apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: E:\bin\kompose.exe convert -f .\docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: angular
  name: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: angular
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: E:\bin\kompose.exe convert -f .\docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: angular
    spec:
      containers:
        - image: tojatos/laser-tactics-frontend-dev
          name: angular
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
