FROM node:16.10.0 AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
RUN npm install -g @angular/cli@~12.2.3
COPY . .

RUN ng build

FROM nginx:1.21.3
COPY --from=build /app/dist/laser-chess-frontend  /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
