name: Frontend CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: npm install
        working-directory: ./laser-chess-frontend
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./laser-chess-frontend
          start: npm start
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 180
      - name: lint game frontend
        working-directory: ./laser-chess-frontend
        run: npm run lint
